ports:
  websecure:
    tls:
      certResolver: leresolver
  web:
    redirectTo: websecure

persistence:
  # persists the /data directory
  enabled: true
  size: 128Mi

logs:
  general:
    level: DEBUG

certResolvers:
  leresolver:
    email: me@alexjball.com
    httpChallenge:
      entrypoint: "web"
    storage: /data/acme.json
    caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

additionalArguments:
  #   - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
  #   - --certificatesresolvers.leresolver.acme.email=me@alexjball.com
  #   # Please note that this is the staging Let's Encrypt server.
  #   # Once you get things working, you should remove that whole line altogether.
  #   - --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
  #   - --certificatesresolvers.leresolver.acme.storage=/data/acme.json
  - --providers.providersthrottleduration=100
